app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', function()
{
	return View::make('hello');
}));


Route::resource('sessions', 'SessionsController');

Route::get('login', array('as' => 'login', 'uses' => 'SessionsController@create'));
Route::get('logout', array('as' => 'logout', 'uses' => 'SessionsController@destroy'));

Route::get('rorytest', function()
{
	$ticket = Ticket::first();
	$user = User::find(1);
	$user2 = User::find(2);

	$ticket->user()->attach(1);
	$ticket->user()->attach(2);

	return $ticket->user;

});


Route::group(array('before' => 'auth'), function(){

	Route::resource('tickets', 'TicketsController');
	Route::get('ticket/{id}', array('as' => 'ticket', 'uses' => 'TicketsController@getTicket'))->where('id', '[1-9][0-9]*');
	Route::get('api/tickets', array('as' => 'api.tickets', 'uses' => 'TicketsController@getTicketsDataTable'));

});


Route::group(array('before' => 'admin_role'), function() {
	Route::resource('admin', 'AdminsController');
	/*Route::get('allusers',array('as' => 'allusers', 'uses' => 'AdminsController@users'));
	
	Route::get('api/users', array('as' => 'api.allusers', 'uses' => 'AdminsController@getUsersDataTable'));*/
	Route::resource('users', 'UsersController');
	Route::get('users',array('as' => 'users', 'uses' => 'UsersController@users'));
	Route::get('api/users', array('as' => 'api.users', 'uses' => 'UsersController@getUsersDataTable'));
	Route::get('alltickets', array('as' => 'all.tickets', 'uses' => 'AdminsController@tickets'));
	Route::get('api/alltickets', array('as' => 'api.alltickets', 'uses' => 'AdminsController@getTicketsDataTable'));
	Route::resource('locations', 'LocationsController');
	Route::get('locations', array('as' => 'locations', 'uses' => 'AdminsController@locations'));
	Route::get('api/locations', array('as' => 'api.locations', 'uses' => 'AdminsController@getLocationsDataTable'));
	
	
	

});

app/views/admins/create.blade.php
/home/vagrant/Code/unco/app/views/admins/create.blade.php

app/views/admins/edit.blade.php
/home/vagrant/Code/unco/app/views/admins/edit.blade.php

app/views/admins/index.blade.php
@extends('_layouts.index')
@section('content')

<div class="row">
  <div class="col-md-12">
  <h1>Welcome</h1>
  <h2>{{ link_to_route("all.tickets", 'Tickets')}}</h2>
  <h2>{{ link_to_route("users", 'Users')}}</h2>
  <h2>{{ link_to_route("locations", 'Locations')}}</h2>
 
  </div>
</div>
@stop

app/views/admins/newuser.blade.php
@extends('_layouts.index')


@section('content')
<h1 data-localize = main.NewUser>Create a new user</h1>

{{ Form::open(array('route' => 'users.store'))}}

                      <fieldset>
		<div class="form-group">
		<label data-localize = "main.Name" class="col-sm-2 control-label">Name</label>
         <div class="col-sm-10">

		
	{{ Form::text('name', $value = null, array('data-localize' => 'main.Name', 'placeholder' => 'name', 'type'=>'text', 'class' => 'form-control'))}}
		
  </div>
                        </div>
                     </fieldset>
	        <fieldset>
		<div class="form-group">
		<label data-localize = "main.Email" class="col-sm-2 control-label">Email</label>
         <div class="col-sm-10">

		
{{ Form::text('email', $value = null, array('data-localize' => 'main.Email', 'placeholder' => 'email', 'type'=>'text', 'class' => 'form-control'))}}
		
  </div>
                        </div>
                     </fieldset>
                     	        <fieldset>
		<div class="form-group">
		<label data-localize = "main.Password" class="col-sm-2 control-label">Password</label>
         <div class="col-sm-10">

		
{{ Form::password('password', array('data-localize' => 'main.Password', 'placeholder' => 'password', 'type'=>'text', 'class' => 'form-control'))}}
		
  </div>
                        </div>
                     </fieldset>

                     <fieldset>  
   <div class="form-group">
                           <label data-localize = "main.Role" class="col-sm-2 control-label">Role</label>
                           <div class="col-sm-10">
		{{ Form::select('role', Role::lists('name', 'id')) }}
		
		</div>
                        </div>
                     </fieldset>
                     
                     <fieldset> 


                                             <div class="form-group">
                           <div class="col-sm-12">
                             
                              {{Form::submit('Save Changes', array('data-localize' => 'main.Save', "class" => "btn btn-primary")) }} 
                           </div>
                        </div>
                     </fieldset>



{{ Form::close() }}
@stop

app/views/admins/show.blade.php
/home/vagrant/Code/unco/app/views/admins/show.blade.php

app/views/admins/tickets.blade.php
@extends('_layouts.index')
@section('content')
 
<div class="row">
  <div class="col-md-12">
  <h1 data-localize="sidebar.Tickets">All Tickets</h1>
  

  <h2>{{ link_to_route('tickets.create', 'New Job', array(), array("data-localize" => "main.NewJob"))}}</h2>
  {{ $table->render() }}
  {{ $table->script() }}
  </div>
</div>
@stop

app/views/admins/users.blade.php
@extends('_layouts.index')
@section('content')


<div class="row">
  <div class="col-md-12">
  <h1 data-localize="sidebar.Users">Users</h1>
  <h2>{{ link_to_route('users.create', 'New User', array(), array('data-localize' => 'main.NewUser'))}}</h2>
 {{ $table->render() }}
  {{ $table->script() }}
  
  </div>
</div>
@stop